---
# tasks file for nginx


- name: Install the latest version of Apache
  apt:
    name: apache2
    update_cache: yes
    state: latest

- name: start Apache
  service:
    name: apache2
    state: started
