---
    - name: Install Python, pip, and MySQL dependencies
      shell: apt-get -y install "{{ item }}"
      with_items:
        - python3-dev
        - default-libmysqlclient-dev
        - build-essential
        - python3
        - python3-pip
        - pkg-config
        - libssl-dev

    - name: Install MySQL server
      shell: apt-get -y install mysql-server

    - name: Install MySQL client
      shell: apt-get -y install mysql-client

    - name: Start the MySQL service
      service:
        name: mysql
        state: started

    - name: Install MySQL Python module for Python 3.x
      pip:
        name: mysqlclient
        executable: pip3   # Use pip3 for Python 3
      become: yes

    - name: Check MySQL user existence
      mysql_user:
        login_user: root
        login_password: "R0)t@1234"
        name: "saranya"
        host: "10.0.%"
        state: absent

    - name: Create MySQL user if it doesn't exist
      mysql_user:
        login_user: root
        login_password: "R0)t@1234"
        name: "saranya"
        host: "10.0.%"
        password: "Saranya@123"
        priv: "*.*:SELECT,INSERT"
        state: present

